### PR TITLE
convert_base()

### PR DESCRIPTION
**Pull request by ShadowStrike-Atomiser**
# What's in this usefulib?
The `convert_base()` function is a Python function that converts a number from one base to another. The function takes three arguments: `from_base`, `to_base`, and `num`. 

`from_base` is an integer that represents the base of the input number. `to_base` is an integer that represents the base to which the input number should be converted. `num` is a string that represents the input number in the `from_base` base.

The function first converts the input number to base 10. It does this by looping through the digits of the input number in reverse order, and for each digit, it multiplies the digit by the appropriate power of the `from_base` base and adds the result to a running total. If the digit is a letter (i.e., not a digit), the function converts it to a number using the ASCII code for the letter.

Once the input number has been converted to base 10, the function converts it to the new base. It does this by repeatedly dividing the base 10 number by the `to_base` base and keeping track of the remainders. If the remainder is less than 10, the remainder is converted to a string and added to the beginning of the result string. If the remainder is 10 or greater, the remainder is converted to a letter using the ASCII code for the letter.The function then returns the string,

## Did you add tests?
Yes.

## Does this solve an issue?
No.

## Checklist
- [ Yes ] Have you followed the [contributing guidelines](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md)?
- [ Yes ] Have you added your usefulib to the [list of usefulibs](https://github.com/hamdivazim/usefulib/blob/main/ALLFUNCTIONS.md)?
- [ Yes ] Have you added a test (or explained why you couldn't above) using the guide [here](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md#writing-tests)?

### CODE REVIEW

**Comment by ShadowStrike-Atomiser** [comment]
@hamdivazim this took me a lot of thinking. I would greatly appreciate it if you could merge (merge any pull requests opened before me first).

**Comment by hamdivazim** [comment]
Ok, also just asking is this another alt account of @MKM12345? You have told me it is not but are you sure?

**Comment by ShadowStrike-Atomiser** [comment]
Yes - I heard of MKM12345 by my friend

**Comment by ShadowStrike-Atomiser** [comment]
Also I have added his changes so that you don't need to merge his pull request.

**Comment by hamdivazim** [comment]
> Yes - I heard of MKM12345 by my friend

Ok so this is not an alt?

**Comment by hamdivazim** [comment]
> Also what do you mean _I_ told you? I never told you anything?

Sorry I meant mkm12345

**Comment by ShadowStrike-Atomiser** [comment]
> > Yes - I heard of MKM12345 by my friend
> 
> Ok so this is not an alt?

No

**Comment by ShadowStrike-Atomiser** [comment]
> > Also what do you mean _I_ told you? I never told you anything?
> 
> Sorry I meant mkm12345

Ok

**Comment by hamdivazim** [comment]
Pls remove mkm's changes as i will just merge his pr and this will cause conflicts

**Comment by ShadowStrike-Atomiser** [comment]
No you dont need to merge his pr - just close it

**Comment by hamdivazim** [comment]
i will ask him before doing so

**Comment by MKM12345** [comment]
Thanks @ShadowStrike-Atomiser! I will close my pr.

**Comment by ShadowStrike-Atomiser** [comment]
No problem @MKM12345!

**Comment by hamdivazim** [comment]
Hi @ShadowStrike-Atomiser, here is some constructive feedback:

* Always use `return` statements and parameters rather than print() and input(). These are intended for use in programs and not for the user.
* Your usefulib looks a bit complicated and hard to read - try adding enters and comments to make it more read, and even better would be to add an example at the top (take `filter_by_condition()` as an example).
* The mocks in the tests are also a bit unnecessary if you use return statements too.
* Use defaults (e.g. keeping base input 2 to 10) as sometimes it can be a bit tedious and monotonous.

Try implementing these then I will be happy to merge this PR. Otherwise, really good job!

**Comment by ShadowStrike-Atomiser** [comment]
Hey @hamdivazim, thanks for the feedback. 

After another long think I have now adjusted the convert_base() to your requirements. Tell me if there's any other issues.

**Comment by ShadowStrike-Atomiser** [comment]
An example of how this might be implemented:
`import usefulib
 from_base = int(input("Enter the base of the number: "))
 to_base = int(input("Enter the base to convert the number to (2-16): "))
 num = input(f"Enter the number in base {from_base}: ")

 result = usefulib.convert_base(from_base, to_base, num)

 print(f"The number in base {to_base} is: {result}")

**Comment by hamdivazim** [comment]
Perfect! I will review your changes again soon.

**Comment by hamdivazim** [comment]
@MKM12345 during reviews I noticed your scripts are not working properly due to incorrect setup. You need to import `sys` and `numpy` before you can use them - please remember to read the [contributing guidelines](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md) before. Otherwise, not bad :)

**Comment by hamdivazim** [comment]
@MKM12345 your usefulibs have caused a few issues, I will fix them after merging.

**Review by hamdivazim — APPROVED** [review]
Awesome work @ShadowStrike-Atomiser! Your scripts are great and are working fine - the only feedback I have is to try and make it a little more readable. Well done! @MKM12345, your scripts are a bit broken and I will have to fix them. However, the scripts do look like they will work, so great job!

**Comment by ShadowStrike-Atomiser** [comment]
Thanks @hamdivazim!

**Comment by ShadowStrike-Atomiser** [comment]
Also have you fixed MKM12345's issues?

**Comment by MKM12345** [comment]
Thanks @hamdivazim

**Pull request merged**
