### PR TITLE
New functions.

### PR DESCRIPTION
**Pull request by TheCodingLedendofTheNether**
# What's in this usefulib?
In this usefulib are two new functions:
The is_palindrome() function takes a string as input and checks whether it is a palindrome. A palindrome is a word, phrase, number, or sequence of characters that reads the same forward and backward (ignoring punctuation, and capitalization), such as "racecar" or "A man, a plan, a canal, Panama!". The function first converts the input string to lowercase and treats whitespaces as characters. It then checks whether the resulting string is equal to its reverse, and returns True if it is, or False otherwise.

The calculate_fibonacci() function takes a non-negative integer n as input and calculates the nth number in the Fibonacci sequence using recursion. The Fibonacci sequence is a series of numbers in which each number (starting from the third number) is the sum of the two preceding numbers. For example, the first ten numbers in the Fibonacci sequence are 0, 1, 1, 2, 3, 5, 8, 13, 21, and 34. The calculate_fibonacci() function uses recursion to calculate the nth number in the sequence by recursively calling itself with n-1 and n-2 as inputs until it reaches the base case of n=0 or n=1, at which point it returns the corresponding value in the sequence (0 or 1). The function returns the nth number in the sequence.

## Did you add tests?
Yes, I was able to with the (self).

## Does this solve an issue?
No, just adds 2 functions.

## Checklist
- [✅ ] Have you followed the [contributing guidelines](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md)?
- [✅ ] Have you added your usefulib to the [list of usefulibs](https://github.com/hamdivazim/usefulib/blob/main/ALLFUNCTIONS.md)?
- [✅ ] Have you added a test (or explained why you couldn't above) using the guide [here](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md#writing-tests)?

### CODE REVIEW

**Comment by TheCodingLedendofTheNether** [comment]
Hey @hamdivazim, I'm TheCodingLedendofTheNether and I'm about to delete this account. If you want to tell me something, tell me using my main account: MKM12345. Thanks and bye.

**Comment by hamdivazim** [comment]
Cool @MKM12345 thanks

**Comment by MKM12345** [comment]
Please reopen the pr

**Comment by MKM12345** [comment]
Never mind i will open a new pr

**Comment by hamdivazim** [comment]
It closed itself when you deleted the account

**Comment by MKM12345** [comment]
I know that

**Pull request closed without merging**
