### PR TITLE
New get_hash() Function

### PR DESCRIPTION
**Pull request by MKM12345**
# What's in this usefulib?
The get_hash() function is used to calculate the SHA-256 hash of a given string. It takes a string as an argument, puts it in UTF-8 format, and then uses the hashlib library in Python to compute the SHA-256 hash of the encoded string. Finally, it returns the hexadecimal representation of the hash.

## Did you add tests?
I was able to put my function in test.py.

## Does this solve an issue?
No, just adds a new function

## Checklist
- [✅ ] Have you followed the [contributing guidelines](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md)?
- [✅ ] Have you added your usefulib to the [list of usefulibs](https://github.com/hamdivazim/usefulib/blob/main/ALLFUNCTIONS.md)?
- [✅ ] Have you added a test (or explained why you couldn't above) using the guide [here](https://github.com/hamdivazim/usefulib/blob/main/CONTRIBUTING.md#writing-tests)?

### CODE REVIEW

**Comment by MKM12345** [comment]
Also  تَقَبَّلَ اللهُ مِنَّا وَمِنكُم

**Comment by MKM12345** [comment]
An example of usage is this:
```
from _usefulib.py import get_hash

input_password = "password123" # user's input password during login
stored_hash = get_hash(input_password) # hash of the password stored in the system

user_input = input("Enter a password: ")
hashed_input = get_hash(user_input)

if hashed_input == stored_hash:
    print("Correct")
else:
    print("Wrong")
```

**Comment by hamdivazim** [comment]
Is the hashlib library installed using pip?

**Comment by MKM12345** [comment]
> Is the hashlib library installed using pip?

Hashlib has been part of the standard library since python2. 5, released in 2006. You don't need to install it from pypi.

**Comment by hamdivazim** [comment]
Also before I merge could you move the import hashlib in test.py into the setUp method. Thanks for this PR!

**Comment by MKM12345** [comment]
> Also before I merge could you move the import hashlib in test.py into the setUp method. Thanks for this PR!

I have?

**Comment by MKM12345** [comment]
> Also before I merge could you move the import hashlib in test.py into the setUp method. Thanks for this PR!

Also your welcome

**Comment by hamdivazim** [comment]
There is an empty method in the class called setUp() if you could remove the comment and replace that with the import that would be great

**Comment by MKM12345** [comment]
> > Also before I merge could you move the import hashlib in test.py into the setUp method. Thanks for this PR!
> 
> I have?

Oh sorry. Will do when I’m free

**Comment by MKM12345** [comment]
> There is an empty method in the class called setUp() if you could remove the comment and replace that with the import that would be great

Sure, I will do later

**Comment by hamdivazim** [comment]
Alright awesome, will merge when the change is done. Thanks again :)

**Comment by MKM12345** [comment]
> Alright awesome, will merge when the change is done. Thanks again :)

I have been honoured to contribute to a open-source to a Python library. I will ensure the change is done. Thanks and your welcome.

**Comment by hamdivazim** [comment]
Will you do the change or would you like me to do it? I can commit them to this fork.

**Comment by MKM12345** [comment]
> Will you do the change or would you like me to do it? I can commit them to this fork.

No, but thanks any way. I was experiencing some problems when trying to do so and so I just changed the test_get_hash().

**Comment by hamdivazim** [comment]
Oh, the tests were fine, please do use assertEqual. If you would like, I can rewrite the tests for you - try not to use print in tests. Before I merge, could you confirm whether you would want me to do that, or would you like to fix them yourself?

**Comment by MKM12345** [comment]
Thanks - that will be helpful. I'm a little busy so appreciate it.

**Comment by hamdivazim** [comment]
Alright cool - thanks for the PR! Also, could you open discussions on this repository with any questions you have?

**Comment by MKM12345** [comment]
If I do - I'll see if I can.

**Comment by hamdivazim** [comment]
Also @MKM12345, your `get_hash()` usefulib does not catch the error if a string is not inputted. I have added that in for you (this is an example for a good test).

**Comment by MKM12345** [comment]
> Also @MKM12345, your `get_hash()` usefulib does not catch the error if a string is not inputted. I have added that in for you (this is an example for a good test).

Thanks @hamdivazim for this.

**Pull request merged**
